# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Write Properties
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/main/resources/application.properties'
        property: |
          'spring.datasource.url'
          'spring.datasource.username'
          'spring.datasource.password'
          'jwt.secret'
        value: |
          '${{secrets.DB_URL_PROD}}'
          '${{secrets.DB_USERRNAME_PROD}}'
          '${{secrets.DB_PASSWORD_PROD}}'
          '${{secrets.JWT_SECRET_PROD}}'
    - name: Set selected color
      run: cat './src/main/resources/application.properties'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
